auth:
  registry.cn-beijing.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
#   quay.io/jetstack/cert-manager-controller:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-controller
#   quay.io/jetstack/cert-manager-webhook:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-webhook
#   quay.io/jetstack/cert-manager-cainjector:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-cainjector
#   quay.io/jetstack/cert-manager-ctl:v1.9.1,v1.10.2,v1.11.0: registry.cn-beijing.aliyuncs.com/paas-k8s/cert-manager-ctl
#   k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0,v2.5.0: registry.cn-beijing.aliyuncs.com/paas-k8s/local-volume-provisioner
#   k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2: registry.cn-beijing.aliyuncs.com/paas-k8s/nfs-subdir-external-provisioner
#   registry.k8s.io/ingress-nginx/controller:v1.11.2: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-controller
#   registry.k8s.io/ingress-nginx/opentelemetry-1.25.3:v20240813-b933310d: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-opentelemetry-1.25.3
#   registry.k8s.io/ingress-nginx/opentelemetry:v20230107-helm-chart-4.4.2-2-g96b3d2165: registry.cn-beijing.aliyuncs.com/paas-k8s/ingress-nginx-opentelemetry
#   registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.3: registry.cn-beijing.aliyuncs.com/paas-k8s/kube-webhook-certgen
#   registry.k8s.io/defaultbackend-amd64:1.5: registry.cn-beijing.aliyuncs.com/paas-k8s/defaultbackend-amd64
#   goharbor/nginx-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-nginx-photon
#   goharbor/harbor-portal:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-portal
#   goharbor/harbor-core:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-core
#   goharbor/harbor-jobservice:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-jobservice
#   goharbor/registry-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registry-photon
#   goharbor/harbor-registryctl:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-registryctl
#   goharbor/chartmuseum-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-chartmuseum-photon
#   goharbor/trivy-adapter-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-trivy-adapter-photon
#   goharbor/notary-server-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-server-photon
#   goharbor/notary-signer-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-notary-signer-photon
#   goharbor/harbor-db:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-db
#   goharbor/redis-photon:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-redis-photon
#   goharbor/harbor-exporter:v2.7.0: registry.cn-beijing.aliyuncs.com/paas-k8s/harbor-exporter
#  eclipse-temurin:8u472-b08-jdk-alpine,8u472-b08-jre-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:8u472-b08-jdk-noble,8u472-b08-jre-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:17.0.17_10-jre-alpine,17.0.17_10-jdk-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:17.0.17_10-jre-noble,17.0.17_10-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:21.0.9_10-jre-alpine,21.0.9_10-jdk-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:21.0.9_10-jre-noble,21.0.9_10-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:25.0.1_8-jre-alpine,25.0.1_8-jdk-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  eclipse-temurin:25.0.1_8-jre-noble,25.0.1_8-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-amd64
#  maven:3.9.11-eclipse-temurin-25-alpine,3.9.11-eclipse-temurin-25: registry.cn-beijing.aliyuncs.com/officialimage/maven-amd64
#  maven:3.9.11-eclipse-temurin-21-alpine,3.9.11-eclipse-temurin-21: registry.cn-beijing.aliyuncs.com/officialimage/maven-amd64
#  maven:3.9.11-eclipse-temurin-17-alpine,3.9.11-eclipse-temurin-17: registry.cn-beijing.aliyuncs.com/officialimage/maven-amd64
#  maven:3.9.11-eclipse-temurin-8-alpine,3.9.11-eclipse-temurin-8: registry.cn-beijing.aliyuncs.com/officialimage/maven-amd64
#  node:18.20.8-alpine,18.20.8-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-amd64
#  node:20.19.5-alpine,20.19.5-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-amd64
#  node:22.21.1-alpine,22.21.1-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-amd64
#  node:24.11.1-alpine,24.11.1-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-amd64
#  tomcat:8.5.100-jre8-temurin-jammy: registry.cn-beijing.aliyuncs.com/officialimage/tomcat-amd64
#  tomcat:10.1.49-jre17-temurin-noble: registry.cn-beijing.aliyuncs.com/officialimage/tomcat-amd64
#  redis:6.2.20-alpine: registry.cn-beijing.aliyuncs.com/officialimage/redis-amd64
#  redis:7.2.11-alpine: registry.cn-beijing.aliyuncs.com/officialimage/redis-amd64
#  redis/redisinsight:2.70.1: registry.cn-beijing.aliyuncs.com/officialimage/redisinsight-amd64
#  oliver006/redis_exporter:v1.78.0: registry.cn-beijing.aliyuncs.com/officialimage/redis_exporter-amd64
#  mysql:8.0.43-oracle: registry.cn-beijing.aliyuncs.com/officialimage/mysql-amd64
#  prom/mysqld-exporter:v0.17.2: registry.cn-beijing.aliyuncs.com/officialimage/mysqld-exporter-amd64
#  mongo:7.0.28: registry.cn-beijing.aliyuncs.com/officialimage/mongo-amd64
#  mongo-express:1.0.2-20-alpine3.19: registry.cn-beijing.aliyuncs.com/officialimage/mongo-express-amd64
#  percona/mongodb_exporter:0.47.2: registry.cn-beijing.aliyuncs.com/officialimage/mongodb-exporter-amd64
#  postgres:17.6-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/postgres-amd64
#  zookeeper:3.8.4: registry.cn-beijing.aliyuncs.com/officialimage/zookeeper
#  danielqsj/kafka-exporter:v1.9.0: registry.cn-beijing.aliyuncs.com/officialimage/kafka-exporter-amd64
#  apache/kafka:3.9.1: registry.cn-beijing.aliyuncs.com/officialimage/kafka-amd64
  docker.elastic.co/elasticsearch/elasticsearch:8.19.11: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch
  docker.elastic.co/kibana/kibana:8.19.11: registry.cn-beijing.aliyuncs.com/officialimage/kibana
  docker.elastic.co/logstash/logstash:8.19.11: registry.cn-beijing.aliyuncs.com/officialimage/logstash
  docker.elastic.co/beats/metricbeat:8.19.11: registry.cn-beijing.aliyuncs.com/officialimage/metricbeat
#  bitnami/elasticsearch-exporter:1.9.0: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch-exporter
  grafana/grafana:12.3.2: registry.cn-beijing.aliyuncs.com/officialimage/grafana
#  prom/prometheus:v3.9.1: registry.cn-beijing.aliyuncs.com/officialimage/prometheus
#  prom/pushgateway:v1.11.2: registry.cn-beijing.aliyuncs.com/officialimage/pushgateway
#  solr:9.9.0: registry.cn-beijing.aliyuncs.com/officialimage/solr
#  quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z: registry.cn-beijing.aliyuncs.com/officialimage/minio
#  quay.io/minio/mc:RELEASE.2025-05-21T01-59-54Z: registry.cn-beijing.aliyuncs.com/officialimage/minio-mc
#  ollama/ollama:0.6.4: registry.cn-beijing.aliyuncs.com/officialimage/ollama-amd64
#  ghcr.io/open-webui/open-webui:0.6.0: registry.cn-beijing.aliyuncs.com/officialimage/open-webui-amd64
#  nacos/nacos-server:v2.5.1: registry.cn-beijing.aliyuncs.com/officialimage/nacos-server-amd64
#  portainer/portainer-ce:2.31.3-alpine: registry.cn-beijing.aliyuncs.com/officialimage/portainer-ce
#  portainer/agent:2.31.3-alpine: registry.cn-beijing.aliyuncs.com/officialimage/portainer-agent
#  pandoc/extra:3.7.0-ubuntu: registry.cn-beijing.aliyuncs.com/officialimage/pandoc-extra
#  gitlab/gitlab-ce:17.10.8-ce.0: registry.cn-beijing.aliyuncs.com/officialimage/gitlab-ce
