auth:
  registry.cn-beijing.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
#  eclipse-temurin:8u472-b08-jdk-noble,8u472-b08-jre-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  eclipse-temurin:17.0.17_10-jre-noble,17.0.17_10-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  eclipse-temurin:21.0.9_10-jre-alpine,21.0.9_10-jdk-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  eclipse-temurin:21.0.9_10-jre-noble,21.0.9_10-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  eclipse-temurin:25.0.1_8-jre-alpine,25.0.1_8-jdk-alpine: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  eclipse-temurin:25.0.1_8-jre-noble,25.0.1_8-jdk-noble: registry.cn-beijing.aliyuncs.com/officialimage/eclipse-temurin-arm64
#  maven:3.9.11-eclipse-temurin-25-alpine,3.9.11-eclipse-temurin-25: registry.cn-beijing.aliyuncs.com/officialimage/maven-arm64
#  maven:3.9.11-eclipse-temurin-21-alpine,3.9.11-eclipse-temurin-21: registry.cn-beijing.aliyuncs.com/officialimage/maven-arm64
#  maven:3.9.11-eclipse-temurin-17-alpine,3.9.11-eclipse-temurin-17: registry.cn-beijing.aliyuncs.com/officialimage/maven-arm64
#  maven:3.9.11-eclipse-temurin-8-alpine,3.9.11-eclipse-temurin-8: registry.cn-beijing.aliyuncs.com/officialimage/maven-arm64
#  node:18.20.8-alpine,18.20.8-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-arm64
#  node:20.19.5-alpine,20.19.5-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-arm64
#  node:22.21.1-alpine,22.21.1-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-arm64
#  node:24.11.1-alpine,24.11.1-bookworm: registry.cn-beijing.aliyuncs.com/officialimage/node-arm64
#  tomcat:8.5.100-jre8-temurin-jammy: registry.cn-beijing.aliyuncs.com/officialimage/tomcat-arm64
#  tomcat:10.1.49-jre17-temurin-noble: registry.cn-beijing.aliyuncs.com/officialimage/tomcat-arm64
#  redis:6.2.20-alpine: registry.cn-beijing.aliyuncs.com/officialimage/redis-arm64
#  redis:7.2.11-alpine: registry.cn-beijing.aliyuncs.com/officialimage/redis-arm64
#  redis/redisinsight:2.70.1: registry.cn-beijing.aliyuncs.com/officialimage/redisinsight-arm64
#  oliver006/redis_exporter:v1.78.0: registry.cn-beijing.aliyuncs.com/officialimage/redis_exporter-arm64
  mysql:8.0.45-oracle: registry.cn-beijing.aliyuncs.com/officialimage/mysql-arm64
  prom/mysqld-exporter:v0.18.0: registry.cn-beijing.aliyuncs.com/officialimage/mysqld-exporter-arm64
#  mongo:7.0.29: registry.cn-beijing.aliyuncs.com/officialimage/mongo-arm64
#  mongo-express:1.0.2-20-alpine3.19: registry.cn-beijing.aliyuncs.com/officialimage/mongo-express-arm64
#  percona/mongodb_exporter:0.47.2: registry.cn-beijing.aliyuncs.com/officialimage/mongodb-exporter-arm64
#  zookeeper:3.8.6: registry.cn-beijing.aliyuncs.com/officialimage/zookeeper
#  danielqsj/kafka-exporter:v1.8.0: registry.cn-beijing.aliyuncs.com/officialimage/kafka-exporter-arm64
#  apache/kafka:3.8.1: registry.cn-beijing.aliyuncs.com/officialimage/kafka-arm64
#  docker.elastic.co/elasticsearch/elasticsearch:8.14.3: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch
#  docker.elastic.co/kibana/kibana:8.14.3: registry.cn-beijing.aliyuncs.com/officialimage/kibana
#  docker.elastic.co/logstash/logstash:8.14.3: registry.cn-beijing.aliyuncs.com/officialimage/logstash
#  docker.elastic.co/beats/metricbeat:8.14.3: registry.cn-beijing.aliyuncs.com/officialimage/metricbeat
#  bitnami/elasticsearch-exporter:1.7.0: registry.cn-beijing.aliyuncs.com/officialimage/elasticsearch-exporter
#  grafana/grafana:11.1.4: registry.cn-beijing.aliyuncs.com/officialimage/grafana
#  prom/prometheus:v2.53.2: registry.cn-beijing.aliyuncs.com/officialimage/prometheus
#  prom/pushgateway:v1.9.0: registry.cn-beijing.aliyuncs.com/officialimage/pushgateway
#  solr:9.6.1: registry.cn-beijing.aliyuncs.com/officialimage/solr
#  quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z: registry.cn-beijing.aliyuncs.com/officialimage/minio
#  quay.io/minio/mc:RELEASE.2024-08-13T05-33-17Z: registry.cn-beijing.aliyuncs.com/officialimage/minio-mc

















